### PR TITLE
Config delays

### LINKED ISSUE #26: Make Delay Configurable
Right now, there is a delay of 1 second for every message the bot says. It would be nice if it was configurable, e.g. so that I can turn it off during debugging.

### LINKED ISSUE #28: Use credentials in fetch() call
The chatroom doesn't currently work if HTTP authentification is used.
Use `fetch(url, { credentials: 'include' })` in all `fetch()` calls.

### PR DESCRIPTION
**Pull request by normanrz**
Exposes configuration parameters:
- Polling Interval
- Waiting timeout (i.e. message delay)
- Fetch options (useful for `{ credentials: 'include' }`

Fixes #28 
Fixes #26

### CODE REVIEW

**Comment by hotzenklotz** [comment]
@georgwiese Yes, it is auto deployed to AWS with CircleCI. 

You don't have to change the link if you use `@master`Otherwise you can specify the version explicitly. E.g. `chatroom@0.1.5`

**Comment by normanrz** [comment]
Deployed as `0.7.3`

**Comment by xi1570-krupeshanadkat** [comment]
If i want to have 2 seconds delay before i get response from bot, what should I do?
```html
<script src="https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.js"></script>
  <script type="text/javascript">
    var chatroom = new window.Chatroom({
      host: "http://localhost:5005",
      title: "Xebia FAQ Bot",
      container: document.querySelector(".chat-container"),
      welcomeMessage: "FAQ Chatbot",
      speechRecognition: "en-US",
      waitingTimeout: 2000   // <- this isn't working.
    });
    chatroom.openChat();
  </script>
```

**Comment by hotzenklotz** [comment]
@xi1570-krupeshanadkat I believe the `waitingTimeout` may work differently than you imagine. Upon sending a user message to the bot backend a loading spinner is shown. In cases were the server takes to long to respond or does not respond at all this loading spinner will never go away. The `waitingTimeout` is the maximum time before this spinner will disappear regardless of the server response.

**Pull request merged**
